name = "rtsda-web"
compatibility_date = "2024-11-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "directory"

[site]
bucket = ".vercel/output/static"

[[rules]]
type = "Rule"
glob = "/*"
fallthrough = true

[[rules]]
type = "Rule"
glob = "/_next/*"
cache_key = "next-static"
[rules.cache]
browser_ttl = 31536000
edge_ttl = 31536000

[[rules]]
type = "Rule"
glob = "/static/*"
cache_key = "static-assets"
[rules.cache]
browser_ttl = 31536000
edge_ttl = 31536000
