name = "rtsda-web"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "rtsda-web-assets"

[env.production]
vars = { ENVIRONMENT = "production" }

[observability]
[observability.logs]
enabled = true
