name = "rtsda-web"
main = "worker/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" }
